version: 2
jobs:
  build:
    docker:
      - image: python:2-alpine
    steps:
      - checkout
      - run:
          name: Build steps
          command: |
            python -m py_compile sources/add2vals.py sources/calc.py
  test:
    docker:
      - image: qnib/pytest
    steps:
      - checkout
      - run:
           name: Run Tests
           command: |
             py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py
      - store_test_results:
          path: test-reports
  deliver:
    docker:
      - image: cdrx/pyinstaller-linux:python2
    steps:
      - checkout
      - run:
          name: Deliver build
          command: |
            whoami
            pwd
            ls -al ~/.pyenv/shims/
            pip
            pyinstaller --onefile sources/add2vals.py
      - store_artifacts:
          path: dist/add2vals
          destination: build

workflows:
  version: 2
  full_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deliver:
          requires:
            - hold
